### ISSUE TITLE
°C | °F links are not working in the 2nd row

### ISSUE THREAD

**Issue by gokaygurcan** [GoksenCodes/Weather-today-project#1]
Hiya, 

<img width="783" alt="Screenshot 2020-01-17 at 14 30 58" src="https://user-images.githubusercontent.com/1509413/72615885-fc781700-3935-11ea-9821-947bcced4307.png">

There are actually 2 problems, probably they are related.

- In the 2nd row, you cannot switch between C and F. It jumps to the top and doesn't change the value.
- When you switch from C to F, it updates all values to F but you cannot switch back to C in the second row anymore (see screenshot for clear picture). 

I hope this will help.

Cheers,
G.

**Comment by GoksenCodes** [comment]
I added the switching back to C feature and removed the C & F links from forecast section. I think removing the links is the best solution from the perspective of usability, user can control the unit they want to see from the current weather section.
